name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: sawertyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      -
        name: Build
        id: docker_build
        run: make
      -
        name: Push
        run: docker push -a sawertyu/modern_python
